config/routes.rb
Retros::Application.routes.draw do
  
  resources :retros
  
  root to: 'retros#index'
  
  resources :items

  get '/welcome' => 'pages#home', :as => :welcome
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  
  has_many :items
  
  def self.aha
    find_by_name 'aha'
  end
  
  def self.fuzzy
    find_by_name 'fuzzy'
  end
  
  
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :category_id, :note, :retro_id
  
  belongs_to :category
  belongs_to :retro

  def self.for_category(category)
    where(category_id: category.id)
  end
end

app/models/motto.rb
class Motto
  
  MOTTOS = [
    "We are uncovering better ways of developing software
    by doing it and helping others do it.",
      
    "We value individuals and interactions
    over processes and tools.",
    "We value working software 
    over comprehensive documentation",
    "We value customer collaboration
    over contract negotiation.",
    "We value responding to change
    over following a plan.",
    "Our highest priority is to satisfy the customer
    through early and continuous delivery
    of valuable software.",
    
    "Welcome changing requirements, even late in 
    development. Agile processes harness change for 
    the customer's competitive advantage.",

    "Deliver working software frequently, from a 
    couple of weeks to a couple of months, with a 
    preference to the shorter timescale.",

    "Business people and developers must work 
    together daily throughout the project.",

    "Build projects around motivated individuals. 
    Give them the environment and support they need, 
    and trust them to get the job done.",

    "The most efficient and effective method of 
    conveying information to and within a development 
    team is face-to-face conversation.",

    "Working software is the primary measure of progress.",

    "Agile processes promote sustainable development. 
    The sponsors, developers, and users should be able 
    to maintain a constant pace indefinitely.",

    "Continuous attention to technical excellence 
    and good design enhances agility.",

    "Simplicity--the art of maximizing the amount 
    of work not done--is essential.",

    "The best architectures, requirements, and designs 
    emerge from self-organizing teams.",

    "At regular intervals, the team reflects on how 
    to become more effective, then tunes and adjusts 
    its behavior accordingly.",

    
    ]
  
  def self.sample
    MOTTOS.sample.html_safe
  end
  
end

app/models/retro.rb
class Retro < ActiveRecord::Base
  attr_accessible :captured_on
  
  has_many :items, dependent: :destroy
  
  validates_presence_of :captured_on
  
  def stats
    [items.for_category(Category.fuzzy).count,
      items.for_category(Category.aha).count]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  def create
    @item = Item.new(params[:item])
    if @item.save
      respond_to do |format|
        format.html { redirect_to retro_url(@item.retro) }
      end
    else
      logger.warn "Whoa!"
      logger.warn item.inspect
    end
  end
  
  def destroy
    @item = Item.find(params[:id])
    if @item
      @item.destroy
      respond_to do |format|
        format.html { redirect_to retro_url(@item.retro) }
      end
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  skip_before_filter :require_login
  
  def home
    
  end
  
end

app/controllers/retros_controller.rb
class RetrosController < ApplicationController

  def create
    retro = Retro.create captured_on: Date.today
    redirect_to retro, notice: "You've created a new retrospective!"
  end
  
  def update
    retro = Retro.find(params[:id])
    retro.update_attributes(params[:retro])
    
    respond_to do |format|
      format.js 
    end
  end
  
  def index
  end
  
  def destroy
    retro = Retro.find(params[:id])
    retro.destroy if retro
    redirect_to retros_url, notice: "That retro is toast!"
  end
  
  def show
    @retro = Retro.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    
  end
  
  def create
    incoming_name = params[:user][:nickname].strip.delete('@')
    if !User.find_by_nickname(incoming_name)
      @user = organization.users.create nickname: incoming_name, provider: 'twitter'
      
      respond_to do |format|
        format.html { redirect_to users_url(subdomain: 'www', notice: 'New  user added!') }
        format.js
      end
    else
      respond_to do |format|
        format.html { redirect_to users_url(subdomain: 'www', notice: "User already exists.") }
        format.js { head :ok }
      end
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url(subdomain: 'www') }
      format.js
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def signin_url
    if Rails.env.development?
      'auth/developer'
    else
      'auth/twitter'
    end
  end
end

app/views/items/_item.html.haml
%li.note{:id => dom_id(item)}
  = item.note
  = link_to item_url(item), method: 'delete', class: 'trash_icon' do
    %i.icon-trash
    
  

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "TeamRetros"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = stylesheet_link_tag "http://code.jquery.com/ui/1.9.2/themes/redmond/jquery-ui.css", :media => "screen"
    
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114")
    
    
  %body
    .navbar.navbar-fixed-top.navbar-inverse
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#{root_url}") Starter League Retros
                
    .container

      .content
        .row
          - if flash[:notice]
            .span12#notice.alert.alert-success= notice
          - else
            .span12#notice
            
        .row
          .span12
            = yield
    
      %footer
        = render 'pages/motto'
      
    

app/views/pages/_motto.html.haml
%blockquote.pull-right#motto
  = simple_format Motto.sample
  %small The Agile Manifesto

app/views/pages/home.html.haml
.hero-unit.span11
  %h1 Welcome!

  %p= link_to "Sign In With Twitter to Get Started", signin_url, :class => 'btn btn-primary btn-large'
  

app/views/retros/_quadrant.html.haml
.notes
  %h1
    = category.name.upcase
    = render 'stat_info', :category => category, :item_count => @retro.items.for_category(category).count

    = form_for @retro.items.for_category(category).new do |f|
      = f.text_field :note, :id => "note_for_#{category.name.downcase}"
      = f.hidden_field :category_id
      = f.hidden_field :retro_id
    
  %ul.unstyled(id="#{dom_id(category)}")
    - @retro.items.for_category(category).each do |item|
      = render 'items/item', :item => item
      

app/views/retros/_stat_info.html.haml
- labels = { :aha => :success, :fuzzy => :important}

%span.statcount.label(id="stat_#{dom_id(category)}" class="label-#{labels[category.name.downcase.to_sym]}")= item_count

app/views/retros/index.html.haml
.page-header 
  %h1 All Retrospectives
  
.row
  .span6
    %p
      = link_to "Capture a New Retro", @retro, method: 'post', class: 'btn btn-success'
  
  
    %table.table.table-striped
      %thead
        %th Capture Date
        %th Stats
      %tbody
        - Retro.order('captured_on desc').limit(100).each do |retro|
          %tr
            - stats = retro.stats
            %td
              = link_to retro_url(retro) do
                View
                = retro.captured_on.to_formatted_s(:long)
            %td
              %span.label.label-success.stat= stats.first
              %span.label.label-important.stat= stats.second


  

app/views/retros/show.html.haml
.page-header 
  %h1
    %small Retrospective No. #{@retro.id}

.row
  .span12
    = form_for @retro, remote: true, html: { class: 'well form-inline' } do |f|
      = f.label :captured_on
      = f.text_field :captured_on, :class => 'input-small'

      = f.submit "Save", :class => 'btn-info btn'

      %p.pull-right
        = link_to "Delete This Retrospective", @retro, method: 'delete', confirm: 'Are you sure?  There is no going back!', class: 'btn btn-danger'
        = link_to "I'm Done", retros_url, class: 'btn btn-success'

.row
  .span12#page_notice

    
#retrobox

  .row.top_side
    .span6.left_side
      = render 'quadrant', :category => Category.aha
    .span6.right_side
      = render 'quadrant', :category => Category.fuzzy